# Generated by Django 3.0.14 on 2021-09-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок новости')),
                ('news_text', models.TextField(verbose_name='Текст новости')),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Дата опубликования')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion_title', models.CharField(max_length=250, unique=True, verbose_name='Вопрос в краткой форме')),
                ('description', models.CharField(max_length=1000, unique=True, verbose_name='Подробное описание вопроса')),
                ('answer', models.CharField(max_length=1000, unique=True, verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Вопросы 2',
            },
        ),
        migrations.AlterModelOptions(
            name='cuponi',
            options={'verbose_name': 'Название купона', 'verbose_name_plural': 'Название купонов'},
        ),
        migrations.AlterField(
            model_name='cuponi',
            name='cupon_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название купона'),
        ),
        migrations.AlterField(
            model_name='cuponi',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
